---
version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper-sasl-plain-tls-all-connections
    environment:
      ZOO_MY_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SASL_ENABLED: "false"
    healthcheck:
      test: nc -z localhost 2181 || exit 1
      interval: 10s
      retries: 10
      start_period: 15s
      timeout: 10s

  kafka-broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka-broker-sasl-plain-tls-all-connections
    ports:
      - "9094:9094"
      - "29094:29094"
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: SASL_SSL://0.0.0.0:9094, PLAINTEXT://0.0.0.0:29094
      KAFKA_ADVERTISED_LISTENERS: SASL_SSL://localhost:9094, PLAINTEXT://localhost:29094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/broker_jaas.conf"
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.server.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: ssl_keystore_credentials
      KAFKA_SSL_KEY_CREDENTIALS: ssl_key_credentials
      KAFKA_SSL_ENABLED_PROTOCOLS: TLSv1.2,TLSv1.1,TLSv1
      KAFKA_LOG4J_ROOT_LOGLEVEL: DEBUG
    volumes:
      - ./broker_jaas.conf:/etc/kafka/broker_jaas.conf
      - ./server.keystore.jks:/etc/kafka/secrets/kafka.server.keystore.jks
      - ./ssl_key_credentials:/etc/kafka/secrets/ssl_key_credentials
      - ./ssl_keystore_credentials:/etc/kafka/secrets/ssl_keystore_credentials
    healthcheck:
      test: nc -z localhost 9094 || exit 1
      interval: 30s
      retries: 10
      start_period: 15s
      timeout: 10s
