---
version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper-sasl-plain-no-tls
    environment:
      ZOO_MY_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SASL_ENABLED: "false"
    healthcheck:
      test: nc -z localhost 2181 || exit 1
      interval: 10s
      retries: 10
      start_period: 15s
      timeout: 10s

  kafka-broker:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka-broker-sasl-plain-no-tls
    ports:
      - "9093:9093"
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_LISTENERS: SASL_PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/broker_jaas.conf"
    volumes:
      - ./broker_jaas.conf:/etc/kafka/broker_jaas.conf
    healthcheck:
      test: nc -z localhost 9093 || exit 1
      interval: 30s
      retries: 10
      start_period: 15s
      timeout: 10s